# Generated by Django 5.0.4 on 2024-04-09 19:09

import django.core.validators
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("price", models.FloatField(verbose_name="Price")),
                (
                    "image",
                    models.FileField(
                        upload_to=products.models.resume_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
